server:
  port: 8080
  servlet:
    context-path: /
spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: file:/Users/ben.wangz/develop/learning/flink-learnning/visualization/integration/build/frontend
